# Generated by Django 5.1.1 on 2024-09-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genecounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleID', models.PositiveIntegerField()),
                ('geneName', models.CharField(max_length=50)),
                ('counts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group', models.CharField(max_length=2)),
                ('sex', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Genesummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneName', models.CharField(max_length=50)),
                ('totalNum', models.PositiveIntegerField()),
                ('novelNum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Transcriptcounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleID', models.PositiveIntegerField()),
                ('geneName', models.CharField(blank=True, max_length=50, null=True)),
                ('isoform', models.CharField(max_length=50)),
                ('counts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group', models.CharField(max_length=2)),
                ('sex', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expression.genre')),
            ],
        ),
    ]
