# Generated by Django 5.1.1 on 2024-09-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqname', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('feature_type', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('strand', models.CharField(max_length=1)),
                ('frame', models.CharField(blank=True, max_length=1, null=True)),
                ('attributes', models.TextField()),
            ],
        ),
    ]
