# Generated by Django 5.1.1 on 2024-09-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0003_transcriptgtffeature_delete_transcriptfeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptgtffeature',
            old_name='gene_id',
            new_name='geneName',
        ),
        migrations.RenameField(
            model_name='transcriptgtffeature',
            old_name='transcript_id',
            new_name='transcriptName',
        ),
    ]
