# Generated by Django 5.1.1 on 2024-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0004_rename_gene_id_transcriptgtffeature_genename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqname', models.CharField(max_length=100)),
                ('geneName', models.CharField(max_length=100)),
                ('isoform', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('feature', models.CharField(max_length=100)),
                ('strand', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='TranscriptGtfFeature',
        ),
    ]
