# Generated by Django 5.1.1 on 2024-09-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0005_transcriptfeature_delete_transcriptgtffeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcriptfeature',
            old_name='seqname',
            new_name='seqnames',
        ),
    ]
